import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { Sidebar } from "@/components/sidebar";
import SidebarMobile from "@/components/sidebar-mobile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className + "bg-background text-foreground"}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div className="grid h-screen max-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
                        <Sidebar />
                        <div className="flex flex-col max-h-screen relative">
                            <SidebarMobile />
                            {/* <main className="flex flex-1 flex-col gap-4 lg:gap-6"> */}
                            {children}
                            {/* </main> */}
                        </div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
